---
title: "Lab3 C.Thomas"
author: "Charlene Thomas"
date: "October 2, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

#Assignment for Lab 3
1. Read Chapter 19 from “R for data science” (online version).
Completed! 

2. Create a GitHub repository Lab3 (files with R code for the assignment should be added to this
repository)

Completed! 

3. Complete Problem 2 from “Activity for Lab 3”.

```{r}
library(tidyverse)
library(gapminder) 
gapminder %>%
  filter(year == 2007) %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point() + 
  geom_text(aes(label = ifelse(gdpPercap > 40000 & continent == "Europe",
                               as.character(country), '')),
            color = "blue", vjust = 1.5) +
  xlab("GDP per capita") +
  ylab("life expectancy") +
  theme_bw()
```

4. Modify your R code for the previous problem and recreate the graph:
```{r, fig.height = 6}
library(tidyverse)
library(gapminder) 
gapminder %>%
  filter(year == 2007) %>% 
  ggplot(aes(x = gdpPercap, y = lifeExp)) + 
  geom_point(shape = 1, stroke = 1.5, size =2) +
  annotate("rect", xmin = 39000, xmax = 51000, 
           ymin = 75, ymax = 85, alpha = 0.20, fill = "red") +
  annotate("text", label = "Countries with \n highest GDP", 
           x = 45000, y = 75,  size=4, vjust = 1.1) +
  xlab("GDP per capita") +
  ylab("life expectancy") +
  theme_bw()

```
